document.addEventListener('DOMContentLoaded', () => {
  const root = document.documentElement;
  const profiles = window.TBSProfiles;
  const initials = name => String(name || 'TB').trim().split(/\s+/).slice(0, 2).map(x => x[0]).join('').toUpperCase() || 'TB';
  const current = () => profiles?.getActive() || {};
  const photoOf = p => profiles?.photo(p) || '';
  const setAvatar = (element, p) => { if (!element) return; const src = photoOf(p); element.innerHTML = src ? `<img src="${src}" alt="รูปโปรไฟล์">` : initials(p.fullName || p.displayName); };
  const money = n => `฿${Number(n || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  const today = () => new Date().toISOString().slice(0, 10);
  const formatDate = value => { if (!value) return 'เลือกช่วงวันที่'; const [y, m, d] = value.split('-'); return `${d}/${m}/${y}`; };
  const defaultRange = () => { const end = today(); const start = new Date(); start.setDate(start.getDate() - 29); return { from: start.toISOString().slice(0, 10), to: end }; };
  const readRange = () => { try { const r = JSON.parse(localStorage.getItem('cw_home_date_range') || 'null'); return r?.from && r?.to ? r : defaultRange(); } catch { return defaultRange(); } };
  const saveRange = r => localStorage.setItem('cw_home_date_range', JSON.stringify(r));
  const setTheme = theme => { root.dataset.theme = theme; localStorage.setItem('incentive_theme', theme); document.querySelectorAll('.theme-icon').forEach(x => x.textContent = theme === 'dark' ? 'light_mode' : 'dark_mode'); };
  setTheme(localStorage.getItem('incentive_theme') || 'light');
  document.querySelector('.theme-toggle')?.addEventListener('click', () => setTheme(root.dataset.theme === 'dark' ? 'light' : 'dark'));

  function showView(target) {
    const safeTarget = target === 'view-summary' || target === 'view-dashboard' ? 'view-history' : target;
    document.querySelectorAll('.view-section').forEach(v => v.classList.toggle('active', v.id === safeTarget));
    document.querySelectorAll('[data-target]').forEach(n => n.classList.toggle('active', n.dataset.target === safeTarget && n.classList.contains('nav-item')));
    if (safeTarget === 'view-home') renderHome();
  }
  document.querySelectorAll('[data-target]').forEach(link => link.addEventListener('click', e => { e.preventDefault(); if (link.dataset.vehicle) window.dispatchEvent(new CustomEvent('vehicleSelected', { detail: link.dataset.vehicle })); showView(link.dataset.target); }));
  window.addEventListener('showView', e => showView(e.detail));

  function fillForm(p) { [['profile-name', 'fullName'], ['profile-email', 'email'], ['profile-hub', 'hub'], ['profile-position', 'position'], ['profile-employee', 'employeeId'], ['profile-driver', 'driverId']].forEach(([id, key]) => { const el = document.getElementById(id); if (el) el.value = p?.[key] || ''; }); }
  function renderProfileList() { const list = document.getElementById('profile-list'); if (!list) return; const active = current(), all = profiles?.all() || []; if (!all.length) { list.innerHTML = '<div class="empty-profile">ยังไม่มีโปรไฟล์ในเครื่อง</div>'; return; } list.innerHTML = all.map(p => `<div class="profile-row ${p.profileId === active?.profileId ? 'active' : ''}" data-profile-id="${p.profileId}"><span class="profile-row-avatar">${photoOf(p) ? `<img src="${photoOf(p)}" alt="">` : initials(p.fullName || p.displayName)}</span><span class="profile-row-main"><b>${p.fullName || p.displayName || 'ไม่มีชื่อ'}</b><small>${p.hub || 'ยังไม่ระบุ Hub'} · ${p.position || 'ยังไม่ระบุตำแหน่ง'}</small></span>${p.profileId === active?.profileId ? '<span class="active-label">ใช้งานอยู่</span>' : ''}<button type="button" class="icon-button profile-edit" data-edit-profile="${p.profileId}" aria-label="แก้ไขโปรไฟล์"><span class="material-icons-round">edit</span></button>${p.profileId !== active?.profileId ? `<button type="button" class="icon-button profile-delete" data-delete-profile="${p.profileId}" aria-label="ลบโปรไฟล์"><span class="material-icons-round">delete</span></button>` : ''}</div>`).join(''); list.querySelectorAll('[data-profile-id]').forEach(row => row.addEventListener('click', e => { if (e.target.closest('button')) return; profiles.setActive(row.dataset.profileId); editingProfileId = row.dataset.profileId; renderProfile(); })); list.querySelectorAll('[data-edit-profile]').forEach(b => b.addEventListener('click', e => { e.stopPropagation(); const p = profiles.all().find(x => x.profileId === b.dataset.editProfile); if (p) { profiles.setActive(p.profileId); editingProfileId = p.profileId; fillForm(p); showView('view-profile'); } })); list.querySelectorAll('[data-delete-profile]').forEach(b => b.addEventListener('click', e => { e.stopPropagation(); if (confirm('ต้องการลบโปรไฟล์นี้หรือไม่?')) { profiles.remove(b.dataset.deleteProfile); editingProfileId = current().profileId || null; renderProfile(); } })); }
  function renderProfile() { const p = current(), name = p.fullName || p.displayName || ''; const greeting = document.getElementById('home-greeting'); if (greeting) greeting.textContent = name ? `สวัสดี, ${name}` : 'เริ่มคำนวณรายได้ของคุณ'; document.querySelectorAll('#home-avatar,#profile-avatar,#calculator-avatar').forEach(x => setAvatar(x, p)); const chip = document.getElementById('calculator-profile-name'); if (chip) chip.textContent = name || 'ยังไม่ได้เลือกโปรไฟล์'; const missing = document.getElementById('calculator-profile-missing'); if (missing) missing.classList.toggle('hidden', Boolean(name && p.hub)); const calcName = document.getElementById('calc-rider'); if (calcName) calcName.value = name; const calcHub = document.getElementById('calc-hub'); if (calcHub) calcHub.value = p.hub || ''; const preview = document.getElementById('profile-preview-name'); if (preview) preview.textContent = name || 'ยังไม่ได้สร้างโปรไฟล์'; fillForm(p); renderProfileList(); }

  function renderHome() {
    const records = window.CWRecordModel ? window.CWRecordModel.readRecords(localStorage) : [], range = readRange();
    const rows = records.filter(r => String(r.date) >= range.from && String(r.date) <= range.to);
    const sum = key => rows.reduce((a, r) => a + (Number(r[key]) || 0), 0);
    const set = (id, value) => { const el = document.getElementById(id); if (el) el.textContent = value; };
    set('home-date-range', `${formatDate(range.from)} – ${formatDate(range.to)}`); set('home-net', money(sum('netIncentive'))); set('home-parcel', sum('parcel').toLocaleString()); set('home-same', sum('sameAddressCount').toLocaleString()); set('home-deduction', money(sum('sameAddressDeduction'))); set('home-rts', money(sum('rtsIncome')));
    const recent = document.getElementById('home-recent'); if (!recent) return; if (!records.length) { recent.className = 'stack-list empty-state'; recent.innerHTML = '<span class="material-icons-round">receipt_long</span><p>ยังไม่มีรายการบันทึก</p>'; return; }
    recent.className = 'stack-list'; recent.innerHTML = records.slice(0, 3).map(r => `<div class="record-card"><span class="record-icon material-icons-round">${r.vehicleType === '2W' ? 'two_wheeler' : 'local_shipping'}</span><div><strong>${r.vehicleType} · Zone ${r.zone}</strong><small>${Number(r.parcel || 0).toLocaleString()} ส่งสำเร็จ · ${r.date}</small></div><div class="record-money">${money(Number(r.netIncentive) || 0)}<small>หัก ${money(Number(r.sameAddressDeduction) || 0)}</small></div></div>`).join('');
  }

  let editingProfileId = current().profileId || null;
  document.getElementById('home-date-picker')?.addEventListener('click', () => { const r = readRange(); document.getElementById('range-from').value = r.from; document.getElementById('range-to').value = r.to; document.getElementById('date-range-editor').classList.remove('hidden'); });
  document.getElementById('range-cancel')?.addEventListener('click', () => document.getElementById('date-range-editor').classList.add('hidden'));
  document.getElementById('range-apply')?.addEventListener('click', () => { const from = document.getElementById('range-from').value, to = document.getElementById('range-to').value; if (!from || !to || from > to) return alert('กรุณาเลือกช่วงวันที่ให้ถูกต้อง'); saveRange({ from, to }); document.getElementById('date-range-editor').classList.add('hidden'); renderHome(); });
  document.getElementById('profile-save')?.addEventListener('click', () => { const old = current(); const p = profiles.save({ firebaseUid: old.firebaseUid, email: document.getElementById('profile-email').value.trim(), displayName: old.displayName || document.getElementById('profile-name').value.trim(), photoURL: old.photoURL || '', customPhoto: old.customPhoto || old.photo || '', fullName: document.getElementById('profile-name').value.trim(), hub: document.getElementById('profile-hub').value.trim(), position: document.getElementById('profile-position').value, employeeId: document.getElementById('profile-employee').value.trim(), driverId: document.getElementById('profile-driver').value.trim() }, editingProfileId); editingProfileId = p.profileId; renderProfile(); alert('บันทึกโปรไฟล์แล้ว'); });
  document.getElementById('profile-new')?.addEventListener('click', () => { editingProfileId = null; fillForm({}); document.getElementById('profile-preview-name').textContent = 'สร้างโปรไฟล์ใหม่'; });
  const photoInput = document.getElementById('profile-photo-input'), choosePhoto = () => photoInput?.click(); document.getElementById('profile-avatar-button')?.addEventListener('click', choosePhoto); document.getElementById('profile-photo-change')?.addEventListener('click', choosePhoto); document.getElementById('profile-photo-remove')?.addEventListener('click', () => { const p = current(); profiles.save({ ...p, customPhoto: '' }, p.profileId); renderProfile(); });
  document.getElementById('profile-manual')?.addEventListener('click', () => showView('view-guide')); document.getElementById('guide-back')?.addEventListener('click', () => showView('view-settings')); document.getElementById('profile-contact')?.addEventListener('click', () => alert('ช่องทางติดต่อจะเปิดให้บริการเร็ว ๆ นี้')); document.getElementById('profile-about')?.addEventListener('click', () => alert('TBS Incentive\nVersion V.1.2\nPowered by #BaNGz'));
  document.getElementById('profile-share')?.addEventListener('click', () => alert('Share App จะเปิดใช้งานหลังสร้าง GitHub Release V1.2 และตรวจสอบ APK URL จริงแล้ว'));
  document.getElementById('profile-support')?.addEventListener('click', () => showView('view-support')); document.getElementById('support-back')?.addEventListener('click', () => showView('view-settings'));
  document.querySelectorAll('.banner-close').forEach(button => button.addEventListener('click', () => button.closest('.profile-autofill-banner,.rts-help')?.classList.add('is-hidden'))); document.getElementById('google-login-button')?.addEventListener('click', () => alert('Google Login ยังรอการตั้งค่า Firebase ของเจ้าของแอป')); document.getElementById('profile-google-card')?.addEventListener('click', () => alert('Google Login ยังรอการตั้งค่า Firebase ของเจ้าของแอป')); document.getElementById('calculator-create-profile')?.addEventListener('click', () => showView('view-profile'));
  window.addEventListener('activeProfileChanged', renderProfile); window.addEventListener('historyUpdated', renderHome); renderProfile(); renderHome();
});
