document.addEventListener('DOMContentLoaded', () => {
  const $ = id => document.getElementById(id);
  const engine = window.CWCalculationEngine;
  const zone = $('calc-zone'), s = $('calc-size-s'), l = $('calc-size-l'), parcel = $('calc-parcel'), same = $('calc-same-address'), rts = $('calc-rts');
  const resultCard = $('export-container');
  const resultFields = {total:$('res-total-parcel'), grand:$('res-grand-total'), gross:$('res-gross'), same:$('res-same'), box:$('res-box'), rts:$('res-rts'), deduction:$('res-deduction'), net:$('res-net'), body:$('breakdown-body'), error:$('calc-error'), save:$('btn-save')};
  let vehicle = '4W';
  const money = n => `฿${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const integer = el => { const n=Number(el?.value); return Number.isInteger(n)&&n>=0?n:null; };
  function initZones(){ zone.innerHTML='<option value="" selected disabled>เลือกโซน</option>'; Object.keys(ZONES_CONFIG).forEach(z=>{const o=document.createElement('option');o.value=z;o.textContent=z;zone.appendChild(o);}); }
  function setVehicle(type){ vehicle=type; document.querySelectorAll('[data-vehicle-tab]').forEach(x=>x.classList.toggle('active',x.dataset.vehicleTab===type)); $('two-w-inputs').classList.toggle('hidden',type!=='2W'); $('four-w-inputs').classList.toggle('hidden',type!=='4W'); $('same-address-rate').textContent=type==='2W'?'อัตราหักบ้านซ้ำ ฿1.50 / ชิ้น':'อัตราหักบ้านซ้ำ ฿2.50 / ชิ้น'; calculate(); }
  function renderBreakdown(rows){ if(!rows?.length){resultFields.body.innerHTML='<tr><td colspan="5" class="empty-cell">กรอกข้อมูลเพื่อดูรายละเอียด</td></tr>';return;} resultFields.body.innerHTML=rows.map(t=>`<tr><td>${t.label}</td><td>${vehicle==='4W'?t.sizeS:'-'}</td><td>${vehicle==='4W'?t.sizeL:t.parcel}</td><td>${vehicle==='4W'?`${t.rateS}/${t.rateL}`:t.rate}</td><td>${money(t.amount)}</td></tr>`).join(''); }
  function calculate(){
    resultFields.error.textContent=''; const z=zone.value; const sameCount=integer(same); const rtsCount=integer(rts) ?? 0; const boxCount=rtsCount; let result=null;
    const entered = Boolean(z || integer(parcel) || integer(s) || integer(l) || sameCount || rtsCount);
    if (!entered) { window.cwCurrentCalculation=null; resultCard?.classList.remove('has-result'); renderBreakdown([]); checkSave(); return; }
    try { if(!engine||!z||sameCount===null||integer(rts)===null){throw new Error('กรุณากรอกข้อมูลให้ครบ');} if(vehicle==='2W'){const p=integer(parcel);if(p===null)throw new Error('จำนวนส่งสำเร็จไม่ถูกต้อง');result=engine.calculate2W(p,z,sameCount);}else{const sv=integer(s),lv=integer(l);if(sv===null||lv===null)throw new Error('จำนวน Size ไม่ถูกต้อง');result=engine.calculate4W(sv,lv,z,sameCount);} result.boxCount=boxCount; result.boxRate=1.5; result.boxAmount=boxCount*1.5; result.rtsCount=rtsCount; result.rtsRate=1.5; result.rtsIncome=rtsCount*1.5; result.netIncentive=Number((result.netIncentive+result.rtsIncome).toFixed(2)); } catch(err){window.cwCurrentCalculation=null;resultCard?.classList.remove('has-result');resultFields.error.textContent=err.message;['total','grand','gross','same','box','rts','deduction','net'].forEach(k=>{if(resultFields[k])resultFields[k].textContent=k==='deduction'?'‑฿0.00':k==='same'||k==='box'||k==='rts'?'0 ชิ้น':k==='total'?'0':'฿0.00';});renderBreakdown([]);checkSave();return;}
    window.cwCurrentCalculation=result; resultCard?.classList.add('has-result'); resultFields.total.textContent=result.parcel.toLocaleString(); resultFields.grand.textContent=money(result.netIncentive); resultFields.gross.textContent=money(result.grossIncentive); resultFields.same.textContent=`${result.sameAddressCount.toLocaleString()} ชิ้น`; resultFields.box.textContent=`${result.boxCount.toLocaleString()} ชิ้น (${money(result.boxAmount)})`; resultFields.rts.textContent=`${result.rtsCount.toLocaleString()} ชิ้น (${money(result.rtsIncome)})`; resultFields.deduction.textContent=`-${money(result.sameAddressDeduction)}`; resultFields.net.textContent=money(result.netIncentive); renderBreakdown(result.tierBreakdown); checkSave();
  }
  function checkSave(){const p=vehicle==='2W'?integer(parcel):(integer(s)||0)+(integer(l)||0);resultFields.save.disabled=!($('calc-date').value&&zone.value&&p>0&&window.cwCurrentCalculation);}
  function reset(){ const keepZone=zone.value||localStorage.getItem('cw_last_zone')||''; $('calculator-form').reset(); zone.value=keepZone; resultCard?.classList.remove('has-result');s.value='0';l.value='0';parcel.value='0';same.value='0';rts.value='0';$('calc-date').valueAsDate=new Date();window.cwCurrentCalculation=null;resultFields.error.textContent='';['total','grand','gross','same','box','rts','deduction','net'].forEach(k=>{if(resultFields[k])resultFields[k].textContent=k==='deduction'?'‑฿0.00':k==='same'||k==='box'||k==='rts'?'0 ชิ้น':k==='total'?'0':'฿0.00';});renderBreakdown([]);checkSave();}
  function loadProfileIntoForm(){}
  document.querySelectorAll('[data-vehicle-tab]').forEach(x=>x.addEventListener('click',()=>setVehicle(x.dataset.vehicleTab)));
  window.addEventListener('vehicleSelected',e=>setVehicle(e.detail));
  window.addEventListener('activeProfileChanged',()=>{loadProfileIntoForm();calculate();});
  [zone,s,l,parcel,same,rts,$('calc-date')].forEach(el=>{el?.addEventListener('input',calculate);el?.addEventListener('change',calculate);});
  $('btn-reset')?.addEventListener('click',reset); initZones(); zone.value=localStorage.getItem('cw_last_zone')||''; zone?.addEventListener('change',()=>localStorage.setItem('cw_last_zone',zone.value)); $('calc-date').valueAsDate=new Date(); loadProfileIntoForm(); setVehicle('4W');
});
