document.addEventListener('DOMContentLoaded', () => {
  const body=document.getElementById('history-body'), save=document.getElementById('btn-save'), sync=document.getElementById('btn-sync-history');
  const money=n=>`฿${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const profile=()=>{try{return JSON.parse(localStorage.getItem('cw_profile')||'{}')}catch{return {}}};
  function load(){if(!body||!window.CWRecordModel)return;const rows=window.CWRecordModel.readRecords(localStorage);if(!rows.length){body.className='stack-list empty-state';body.innerHTML='<span class="material-icons-round">inbox</span><p>ยังไม่มีรายการบันทึก</p>';return;}body.className='stack-list';body.innerHTML=rows.map(r=>`<div class="record-card"><span class="record-icon material-icons-round">${r.vehicleType==='2W'?'two_wheeler':'local_shipping'}</span><div><strong>${r.vehicleType} · Zone ${r.zone}</strong><small>${r.date} · ${r.parcel.toLocaleString()} ส่งสำเร็จ · ${r.fullName||'ไม่ระบุชื่อ'}</small><small>บ้านซ้ำ ${r.sameAddressCount||0} ชิ้น · เงินหัก ${money(r.sameAddressDeduction)}</small></div><div class="record-money">${money(r.netIncentive)}<small>รายได้รวม ${money(r.grossIncentive)}</small></div></div>`).join('');}
  save?.addEventListener('click',()=>{const result=window.cwCurrentCalculation;if(!result){alert('กรุณากรอกข้อมูลและคำนวณก่อนบันทึก');return;}const p=profile();const record=window.CWRecordModel.createRecord({id:Date.now(),date:document.getElementById('calc-date').value,fullName:document.getElementById('calc-rider').value.trim()||p.name||'',hub:document.getElementById('calc-hub').value.trim()||p.hub||'',driverId:p.driverId||'',result,createdAt:new Date().toISOString()});record.synced=false;const raw=window.CWRecordModel.readRawRecords(localStorage);raw.unshift(record);localStorage.setItem('incentive_history',JSON.stringify(raw));load();window.dispatchEvent(new Event('historyUpdated'));const old=save.innerHTML;save.innerHTML='<span class="material-icons-round">check_circle</span>บันทึกสำเร็จ';setTimeout(()=>{save.innerHTML=old;document.getElementById('btn-reset')?.click();},900);});
  sync?.addEventListener('click',async()=>{const raw=window.CWRecordModel.readRawRecords(localStorage), rows=raw.map(window.CWRecordModel.toUnifiedRecord).filter(r=>!r.synced);if(!rows.length){alert('ไม่มีรายการค้างซิงค์');return;}if(!window.APP_CONFIG?.GOOGLE_SCRIPT_URL){alert('ยังไม่ได้ตั้งค่า Sync');return;}sync.disabled=true;try{const ids=new Set(rows.map(r=>r.id));await fetch(APP_CONFIG.GOOGLE_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'saveHistory',data:raw.filter(r=>ids.has(r.id))})});localStorage.setItem('incentive_history',JSON.stringify(raw.map(r=>ids.has(r.id)?{...r,synced:true}:r)));load();alert(`ซิงค์สำเร็จ ${rows.length} รายการ`);}catch(e){alert('ซิงค์ไม่สำเร็จ กรุณาตรวจสอบอินเทอร์เน็ต');}finally{sync.disabled=false;}});
  document.querySelectorAll('.filter-chip').forEach(chip=>chip.addEventListener('click',()=>{document.querySelectorAll('.filter-chip').forEach(x=>x.classList.remove('active'));chip.classList.add('active');const type=chip.textContent.trim();document.querySelectorAll('.record-card').forEach(card=>{card.style.display=type==='ทั้งหมด'||card.textContent.includes(type)?'grid':'none';});}));
  load();
});
